
# This file is a part of Simple-XX/SimpleKernel
# (https://github.com/Simple-XX/SimpleKernel).
#
# workflow.yml for Simple-XX/SimpleKernel.

name: build

on:
  - push
  - pull_request
  - release

env:
  CMAKE_BUILD_TYPE: Release
  DOCKER_IMAGE: ptrnull233/simple_kernel:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Docker image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}

      - name: x86_64
        run: |
            docker run -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} \
            /bin/sh -c "cd /workspace && CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} cmake --preset=build_x86_64 && cmake --build build_x86_64 --target kernel && cmake --build build_x86_64 --target unit-test && cmake --build build_x86_64 --target coverage && cmake --build build_x86_64 --target doc"
          # cmake --preset=build_x86_64
          # cmake --build build_x86_64 --target boot
          # cmake --build build_x86_64 --target kernel
          # cmake --build build_x86_64 --target unit-test
          # cmake --build build_x86_64 --target coverage

      - name: riscv64
        run: |
            docker run -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} \
            /bin/sh -c "cd /workspace && CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} cmake --preset=build_riscv64 && cmake --build build_riscv64 --target kernel"
          # cmake --preset=build_riscv64
          # cmake --build build_riscv64 --target kernel

      - name: aarch64
        run: |
            docker run -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} \
            /bin/sh -c "cd /workspace && CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} cmake --preset=build_aarch64 && cmake --build build_aarch64 --target kernel"
          # cmake --preset=build_aarch64
          # cmake --build build_aarch64 --target boot
          # cmake --build build_aarch64 --target kernel

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{github.workspace}}/build_x86_64/coverage/coverage.info
          verbose: true

      # - name: Build Doc
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     cmake --preset=build_x86_64
      #     cmake --build build_x86_64 --target doc

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ${{github.workspace}}/doc/html

      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
